#!/bin/bash

source hooks/.config

for arch in ${build_architectures[@]}; do
    curl -L https://github.com/multiarch/qemu-user-static/releases/download/v4.2.0-2/qemu-${docker_qemu_arch_map[${arch}]}-static -o qemu-${docker_qemu_arch_map[${arch}]}-static
    chmod 755 qemu-${docker_qemu_arch_map[${arch}]}-static
done
