#!/bin/bash

source hooks/.config

for arch in ${build_architectures[@]}; do
  docker push "${IMAGE_NAME}-${arch}"

  if [ "${arch}" = "amd64" ]; then
    docker tag "${IMAGE_NAME}-${arch}" "${IMAGE_NAME}"
    docker push "${IMAGE_NAME}"
  fi
done
