name: Docker Build
on:
  push:
    branches: [ github-actions ]
  pull_request:
    branches: [ master ]

  workflow_dispatch:

jobs:
  docker-build:
    runs-on: ubuntu-latest
    env:
      IMAGE_NAME: rasmartin/openstack-objectstore-toolkit

    steps:
      - uses: actions/checkout@v2

      - name: Post-Checkout
        run: /bin/bash -c hooks/post_checkout

      - name: Pre-Build
        run: /bin/bash -c hooks/pre_build
      
      - name: Build
        run: /bin/bash -c hooks/build
        