name: Docker Build
on:
  push:
    branches: [ github-actions ]
  pull_request:
    branches: [ master ]

  workflow_dispatch:

jobs:
  docker-build:
    runs-on: ubuntu-latest
    env:
      IMAGE_NAME: rasmartin/openstack-objectstore-toolkit
      REGISTRY: ghcr.io

    steps:
      - name: Checkout
        id: checkout
        uses: actions/checkout@v2

      - name: Login to Registry
        id: docker-login
        if: success()
        uses: docker/login-action@28218f9b04b4f3f62068d7b6ce6ca5b26e35336c
        with:
          registry: ${{ env.REGISTRY}}
          username: ${{ github.actor }}
          password: ${{ github.token }}

      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v1
        with:
          buildx-version: latest
          qemu-version: latest

      - name: Prepare
        id: prepare
        run: |        
          echo ::set-output name=docker_image::${REGISTRY}/${IMAGE_NAME}
          echo ::set-output name=version::${GITHUB_RUN_NUMBER}

      - name: Run Buildx
        id: docker-build
        run: |
          docker buildx build \
            --platform linux/amd64,linux/arm/v6,linux/arm/v7,linux/arm64 \
            --tag ${{ steps.prepare.outputs.docker_image }}:${{ steps.prepare.outputs.version }} \
            --output "type=image,push=true" \
            --file ./Dockerfile .
